language: java
jdk: oraclejdk7

install:
- ./gradlew clean

script:
- ./gradlew check

after_success:
- test ${MAVEN_PUBLISH_USERNAME} && ./gradlew publish

env:
  global:
  - TERM=dumb
  - secure: "Pp9tnWokCpr7v8UMk01RYpBvfFxJpwj/v6Lm/mlth2A7yFaQJweDWzxJat4KD4Cru/FQhYr0Vdgejjo4gXvasaZkPIT6P2woWfKTpdaXjAK3tSoUlLTVX6s6KH8RZSIqS5DdZ9nt6iwNXsAOK8gRONhL0xRb750S3870wAZBxsI="
  - secure: "OEqDEf7xjQgnquPHdWFchuyW3XH1O1pnDe7T3tyQ/Ha3Ys9dPWsqC5R4/rlhRcJogdp12bUiyI3Rm032dCQZsBR7431RB7Ip8ks4sfvG+kCuSn9GQenjwX5+eIm4tXbSS7j84hcpHTzPcSRRAqF6yYhPQXYUjQrKgqKOiRZweuM="
